include: package:pedantic/analysis_options.yaml

# Find a list of all linting rules at
# http://dart-lang.github.io/linter/lints
linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - one_member_abstracts
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps
    - implementation_imports
    - cancel_subscriptions
    - close_sinks

analyzer:
  # exclude:
  #   - path/to/excluded/files/**
  # errors:
  #   invalid_assignment: warning
  #   missing_return: error
  #   dead_code: info
